services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mapache
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data